library;

const Map<int, String> marketDisplayNames = {
  1: 'Toàn trận - 1X2',
  3: 'Toàn trận - Tài xỉu',
  5: 'Toàn trận - Kèo chấp',
  7: 'Toàn trận - Bàn tiếp theo',
  8: 'Toàn trận - Lẻ/Chẵn',
  12: 'Toàn trận - Cơ hội kép',
  16: 'Toàn trận - Hòa hoàn tiền',
  35: 'Đội vô địch',
  36: 'Toàn trận - Cả hai đội ghi bàn',
  58: 'Toàn trận - Đội vào vòng trong',
  59: 'Toàn trận - Đội giao bóng trước',
  60: 'Toàn trận - Cầu thủ bị đuổi khỏi sân',
  76: 'Toàn trận - Lẻ/Chẵn đội nhà',
  77: 'Toàn trận - Lẻ/Chẵn đội khách',
  97: 'Toàn trận - Bàn cuối cùng',
  101: 'Toàn trận - Tài/Xỉu đội nhà',
  102: 'Toàn trận - Tài/Xỉu đội khách',
  103: 'Toàn trận - Đội ghi bàn',
  129: 'Toàn trận - Đội thắng Penalty',
  130: 'Toàn trận - Tài/Xỉu Penalty',
  1006: 'Penalty - Tỷ số chính xác',
  1007: 'Penalty - Tổng số quả thành công',
  1008: 'Penalty - Lượt sút tiếp theo ghi bàn',
  1009: 'Penalty - Tài/Xỉu đội nhà',
  1010: 'Penalty - Tài/Xỉu đội khách',
  1013: 'Penalty - Lẻ/Chẵn',
  1015: 'Penalty - Lẻ/Chẵn đội nhà',
  1016: 'Penalty - Lẻ/Chẵn đội khách',
  1017: 'Penalty - Tỉ số thắng cách biệt',
  69: 'Đội nhà ghi bàn ở cả 2 hiệp',
  70: 'Đội khách ghi bàn ở cả 2 hiệp',
  71: 'Đội nhà thắng cả 2 hiệp',
  72: 'Đội khách thắng cả 2 hiệp',
  73: 'Đội nhà thắng một trong hai hiệp',
  74: 'Đội khách thắng một trong hai hiệp',
  99: 'Cả hai hiệp đều Tài 1.5',
  100: 'Cả hai hiệp đều Xỉu 1.5',
  68: 'Hiệp 1/Toàn trận',
  147: 'Toàn trận - Đội thắng thời gian còn lại',
  152: 'Toàn trận - Kèo chấp châu Âu',
  81: 'Toàn trận - Cả hai đội ghi bàn & Kết quả',
  82: 'Toàn trận - Kết quả & Tổng bàn thắng',
  98: 'Toàn trận - Cả hai đội ghi bàn & Cơ hội kép',
  78: 'Đội nhà thắng giữ sạch lưới',
  79: 'Đội khách thắng giữ sạch lưới',
  87: 'Hiệp nhiều bàn thắng nhất của đội nhà',
  88: 'Hiệp nhiều bàn thắng nhất của đội khách',
  157: 'Toàn trận - Hòa hoàn tiền',
  1018: 'Quả phạt đền tiếp theo ghi bàn',

  2: 'Hiệp 1 - 1X2',
  4: 'Hiệp 1 - Tài xỉu',
  6: 'Hiệp 1 - Kèo chấp',
  9: 'Hiệp 1 - Lẻ/Chẵn',
  13: 'Hiệp 1 - Cơ hội kép',
  37: 'Hiệp 1 - Cả hai đội ghi bàn',
  75: 'Hiệp 1 - Hòa hoàn tiền',
  193: 'Hiệp 1 - Tài/Xỉu đội khách',
  194: 'Hiệp 1 - Tài/Xỉu đội nhà',
  1001: 'Hiệp 1 - Đội nhà giữ sạch lưới',
  1002: 'Hiệp 1 - Đội khách giữ sạch lưới',
  1003: 'Hiệp 1 - Đội thắng thời gian còn lại',
  1004: 'Hiệp 1 - Đội tiếp theo ghi bàn (Châu Âu)',
  195: 'Hiệp 1 - Kèo chấp châu Âu',

  80: 'Hiệp 2 - Tài xỉu',
  85: 'Hiệp 2 - Kèo chấp',
  86: 'Hiệp 2 - Lẻ/Chẵn',
  89: 'Hiệp 2 - 1X2',

  10: 'Tỷ số chính xác',
  11: 'Tỷ số chính xác hiệp 1',
  14: 'Tổng bàn thắng',
  15: 'Tổng bàn thắng hiệp 1',
  132: 'Số bàn thắng chính xác đội nhà',
  133: 'Số bàn thắng chính xác đội khách',

  17: 'Phạt góc - 1X2',
  18: 'Phạt góc H1 - 1X2',
  19: 'Phạt góc - Kèo chấp',
  20: 'Phạt góc H1 - Kèo chấp',
  21: 'Phạt góc - Tài xỉu',
  22: 'Phạt góc H1 - Tài xỉu',
  56: 'Phạt góc Lẻ/Chẵn',
  57: 'Phạt góc Lẻ/Chẵn H1',
  61: 'Phạt góc Tài/Xỉu đội nhà',
  62: 'Phạt góc Tài/Xỉu đội nhà H1',
  63: 'Phạt góc Tài/Xỉu đội khách',
  64: 'Phạt góc Tài/Xỉu đội khách H1',
  66: 'Phạt góc cuối cùng',
  67: 'Phạt góc cuối cùng H1',
  90: 'Phạt góc - Cuộc đua phạt góc',
  91: 'Phạt góc - Cuộc đua phạt góc H1',
  131: 'Tổng phạt góc trận đấu',
  134: 'Tổng phạt góc đội nhà',
  135: 'Tổng phạt góc đội khách',
  136: 'Tổng phạt góc hiệp 1',
  145: 'Phạt góc - Tài/Chính xác/Xỉu',
  140: 'Phạt góc H1 - Tài/Chính xác/Xỉu',
  141: 'Phạt góc hiệp phụ - Tài/Chính xác/Xỉu',
  142: 'Phạt góc hiệp phụ - Tài xỉu',
  144: 'Phạt góc - Kèo chấp châu Âu',
  1005: 'Phạt góc tiếp theo (3 cửa)',
  199: 'Phạt góc tiếp theo (3 cửa) H1',
  198: 'Số phạt góc chính xác đội nhà H1',
  197: 'Số phạt góc chính xác đội khách H1',

  138: 'Thẻ vàng - 1X2',
  139: 'Thẻ vàng - Tài xỉu',
  143: 'Thẻ vàng - Cơ hội kép',
  29: 'Thẻ phạt - 1X2',
  30: 'Thẻ phạt H1 - 1X2',
  31: 'Thẻ phạt - Tài xỉu',
  32: 'Thẻ phạt H1 - Tài xỉu',
  33: 'Thẻ phạt - Kèo chấp',
  34: 'Thẻ phạt H1 - Kèo chấp',

  23: 'Hiệp phụ - 1X2',
  24: 'Hiệp phụ H1 - 1X2',
  25: 'Hiệp phụ - Tài xỉu',
  26: 'Hiệp phụ H1 - Tài xỉu',
  27: 'Hiệp phụ - Kèo chấp',
  28: 'Hiệp phụ H1 - Kèo chấp',
  1011: 'Hiệp phụ - Đội tiếp theo ghi bàn',
  1012: 'Hiệp phụ - Tỷ số chính xác',
  1019: 'Hiệp phụ - Đội thắng thời gian còn lại',

  65: 'Hiệp nhiều bàn thắng nhất',
  146: 'Đội tiếp theo ghi bàn (Châu Âu)',
  148: 'Đội nhà thắng',
  149: 'Đội khách thắng',
  150: 'Đội nhà thắng hoàn tiền',
  151: 'Đội khách thắng hoàn tiền',
  154: 'Có đội thắng',

  153: 'Cầu thủ tiếp theo ghi bàn',
  155: 'Cầu thủ ghi bàn',
  156: 'Cầu thủ ghi từ 2 bàn trở lên',
  158: 'Cầu thủ ghi từ 3 bàn trở lên',
  1026: 'Cầu thủ đội nhà tiếp theo ghi bàn',
  1027: 'Cầu thủ đội khách tiếp theo ghi bàn',

  172: 'Kèo rung 5 phút - Tài/Xỉu',
  167: 'Kèo rung 5 phút - 1X2',
  176: 'Kèo rung 5 phút - Phạt góc kèo chấp',
  171: 'Kèo rung 5 phút - Phạt góc Tài/Xỉu',
  174: 'Kèo rung 5 phút - Phạt góc 1X2',
  164: 'Kèo rung 5 phút - Phạt góc Lẻ/Chẵn',
  177: 'Kèo rung 5 phút - Phạt góc tiếp theo',
  165: 'Kèo rung 5 phút - Đội nhà phạt góc Tài/Xỉu',
  166: 'Kèo rung 5 phút - Đội khách phạt góc Tài/Xỉu',
  173: 'Kèo rung 5 phút - Thẻ Tài/Xỉu',
  175: 'Kèo rung 5 phút - Thẻ 1X2',
  178: 'Kèo rung 5 phút - Đội tiếp theo ghi bàn',
  162: 'Kèo rung 10 phút - Tài/Xỉu',
  168: 'Kèo rung 10 phút - 1X2',
  180: 'Kèo rung 10 phút - Phạt góc kèo chấp',
  161: 'Kèo rung 10 phút - Phạt góc Tài/Xỉu',
  163: 'Kèo rung 10 phút - Phạt góc 1X2',
  179: 'Kèo rung 10 phút - Phạt góc Lẻ/Chẵn',
  190: 'Kèo rung 10 phút - Phạt góc tiếp theo',
  169: 'Kèo rung 10 phút - Đội nhà phạt góc Tài/Xỉu',
  170: 'Kèo rung 10 phút - Đội khách phạt góc Tài/Xỉu',
  160: 'Kèo rung 10 phút - Thẻ Tài/Xỉu',
  159: 'Kèo rung 10 phút - Thẻ 1X2',
  191: 'Kèo rung 10 phút - Đội tiếp theo ghi bàn',
  182: 'Kèo rung 15 phút - Tài/Xỉu',
  181: 'Kèo rung 15 phút - 1X2',
  186: 'Kèo rung 15 phút - Kèo chấp',

  200: 'Toàn trận - Đội thắng',
  201: 'Toàn trận - Kèo chấp',
  202: 'Toàn trận - Tài xỉu',
  203: 'Hiệp 1 - Kèo chấp',
  204: 'Hiệp 1 - Tài xỉu',
  205: 'Hiệp 1 - Đội thắng',
  206: 'Q1 - Đội thắng',
  207: 'Q2 - Đội thắng',
  208: 'Q3 - Đội thắng',
  209: 'Q4 - Đội thắng',
  210: 'Q1 - Kèo chấp',
  211: 'Q2 - Kèo chấp',
  212: 'Q3 - Kèo chấp',
  213: 'Q4 - Kèo chấp',
  214: 'Q1 - Tài xỉu',
  215: 'Q2 - Tài xỉu',
  216: 'Q3 - Tài xỉu',
  217: 'Q4 - Tài xỉu',

  300: 'Đội thắng',
  301: 'Tài xỉu Rounds',
  304: 'Đội thắng',
  305: 'Tài xỉu Rounds',
  306: 'Đội thắng',
  307: 'Tài xỉu Rounds',
  308: 'Kèo chấp',
  309: 'Kèo chấp',
  310: 'Kèo chấp',

  400: 'Toàn trận - Đội thắng',
  401: 'Toàn trận - Tài xỉu Games',
  402: 'Toàn trận - Kèo chấp Games',
  403: 'Toàn trận - Game Winner',
  404: 'Set 1 - Đội thắng',
  405: 'Set 2 - Đội thắng',
  406: 'Set 3 - Đội thắng',
  407: 'Set 4 - Đội thắng',

  500: 'Toàn trận - Đội thắng',
  504: 'Set 1 - Đội thắng',
  505: 'Set 2 - Đội thắng',
  506: 'Set 3 - Đội thắng',
  507: 'Set 4 - Đội thắng',
  508: 'Set 5 - Đội thắng',
  509: 'Toàn trận - Kèo chấp Point',
  510: 'Toàn trận - Tài xỉu Point',

  600: 'Toàn trận - Đội thắng',
  602: 'Ván 1 - Đội thắng',
  603: 'Ván 2 - Đội thắng',
  604: 'Ván 3 - Đội thắng',
  605: 'Ván 4 - Đội thắng',
  606: 'Ván 5 - Đội thắng',
  607: 'Ván 6 - Đội thắng',
  608: 'Ván 7 - Đội thắng',
  609: 'Toàn trận - Kèo chấp Point',
  610: 'Toàn trận - Tài xỉu Point',

  700: 'Toàn trận - Đội thắng',
  709: 'Toàn trận - Kèo chấp Point',
  710: 'Toàn trận - Tài xỉu Point',
};

String marketDisplayName(int marketId) => marketDisplayNames[marketId] ?? 'Market #$marketId';

String resolveTeamNamesInMarketName(String name, {String? homeName, String? awayName}) {
  var result = name;
  if (homeName != null && homeName.isNotEmpty) {
    result = result.replaceAll('Đội nhà', homeName).replaceAll('đội nhà', homeName);
  }
  if (awayName != null && awayName.isNotEmpty) {
    result = result.replaceAll('Đội khách', awayName).replaceAll('đội khách', awayName);
  }
  return result;
}
